config/routes.rb
Rails.application.routes.draw do
  resources :sessions
  resources :users do
    member do
      get :confirm_email
    end
  end

  resources :products
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'pages/about', to: 'pages#about'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/product.rb
class Product < ApplicationRecord
  resourcify
  mount_uploader :image, ImageUploader
  serialize :image, JSON
  belongs_to :user, optional: true

  validates :name, :brand, :category, :price, :image, presence: true
  validates :description, length: {maximum: 100}
  validates :name, length: {maximum: 50}
  validates :brand, length: {maximum: 20}
  validates :category, length: {maximum: 20}
  validates :price, numericality: {only_integer: true}, length: {maximum: 10}

  BRAND = %w{Rode Sony Warm Audio Thomann Yamaha}
  CATEGORY = %w{Guitar Piano Microphone}
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :brand, :description, :category, :price, :image)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.slim
= form_for @product, html: {multipart: true} do |f|
  - if @product.errors.any?
    #error_explanation
      h2 = "#{pluralize(@product.errors.count, "error")} prohibited this product from being saved:"
      ul
        - @product.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :category
    = f.select :category, Product::CATEGORY, prompt: "Select category:"
  .field
    = f.label :brand
    = f.select :brand, Product::BRAND, prompt: "Select brand:"
  .field
    = f.label :description
    = f.text_area :description
	.field
    = f.label :price
    = f.number_field :price
  .field
  	= f.label :image
  	= f.file_field :image
  		- if f.object.image?
  			= image_tag f.object.image.thumb.url
  .actions = f.submit

app/views/products/edit.html.slim
h1 Editing product

== render 'form'

=> link_to 'Show', @product
'|
=< link_to 'Back', products_path

app/views/products/index.html.slim
- @products.each do |product|
  #product-box.border-dark.col-sm-5.col-md-3
    .thumbnail
      = link_to product.image.url do
        = image_tag(product.image.url, :size => "200x200")
		.pa4
			#product_name_index
				= product.name
			#product_info
				p
					strong Brand: 
					= product.brand
				p
					strong Category: 
					= product.category
				p
					strong Description: 
					= product.description
				p
					strong Price: 
					= number_to_currency(product.price, :unit=>'€ ')

app/views/products/new.html.slim
h1 New product

== render 'form'

= link_to 'Back', products_path

app/views/products/show.html.slim
p#notice = notice

p
  strong Name:
  = @product.name
p
  strong Brand:
  = @product.brand
p
  strong Description:
  = @product.description
p
  strong Category:
  = @product.category
p
  strong Price:
  = @product.price
  
p
	strong Image:
	= image_tag @product.image_url

=> link_to 'Edit', edit_product_path(@product)
'|
=< link_to 'Back', products_path