config/routes.rb
Rails.application.routes.draw do
  resources :sessions
  resources :users do
    member do
      get :confirm_email
    end
  end

  resources :products
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'pages/about', to: 'pages#about'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/views/layouts/_navigation.html.slim
header
	.navbar.navbar-inverse.navbar-fixed-top
		.container-fluid
			ul.nav.navbar-nav
				li.active
					li= link_to "Home", root_path
					li= link_to "About us", pages_about_path
					li = link_to "Products", products_path
					- if logged_in? && (can? :create, @product)
						li = link_to "Create Product", new_product_path
			ul.nav.navbar-nav.navbar-right
				- if logged_in?
					li.dropdown
						a.dropdown-toggle data-toggle="dropdown" href="#"
							= current_user.username
							span.caret
						ul.dropdown-menu
							li = link_to content_tag(:span, nil, :class => "glyphicon glyphicon-log-out") + " Logout", logout_path, method: :delete
				- else
					li = link_to content_tag(:span, nil, :class => "glyphicon glyphicon-user") + " Signup", signup_path
					li = link_to content_tag(:span, nil, :class => "glyphicon glyphicon-log-in") + " Login", login_path

app/views/layouts/application.html.slim
doctype html
html
	head
		meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
		title 
    		=> full_title(yield(:title))
		= csrf_meta_tags
		= csp_meta_tag
		= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
		= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
	body
		- flash.each do |type, message|
			div class="alert alert-#{type}"
				= message
		= render 'layouts/navigation'
		= yield